version: "3.8"

services:
  frontend:
    image: docker.io/hsdfat/wedding:latest
    container_name: nextjs-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .env:/app/.env
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wedding-wishes-api
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DB_NAME=wedding_wishes
      - PORT=8080
    volumes:
      - .env:/root/.env
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: wedding-wishes-mongodb
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
volumes:
  mongo-data:

